using System.Globalization;

namespace Heart.Services
{
    /// <summary>全部 UI 字符串。新增语言时在 All 中加一个字典即可。</summary>
    public static class Strings
    {
        private static Dictionary<string, string> Dict(params (string Key, string Value)[] pairs)
        {
            var d = new Dictionary<string, string>();
            foreach (var (key, value) in pairs)
                d[key] = value;
            return d;
        }

        public static readonly Dictionary<string, Dictionary<string, string>> All = new()
        {
            ["zh-CN"] = Dict(
                ("app_title", "心率对比"),
                ("app_file_name", "心率对比"),
                ("nav_devices", "设备"), ("nav_chart", "实时图表"), ("nav_settings", "设置"),
                ("devices_title", "设备"),
                ("scan_devices", "扫描设备"), ("stop_scan", "停止扫描"),
                ("hint_scan", "点击「扫描设备」搜索正在广播心率数据的蓝牙设备"),
                ("hint_scanning", "正在扫描… 已发现 {0} 台设备"),
                ("hint_found", "共发现 {0} 台设备（停止扫描后仍可连接 / 断开）"),
                ("hint_scan_error", "蓝牙扫描启动失败：{0}"),
                ("hint_scan_stopped", "扫描已停止：{0}"),
                ("err_no_radio", "未检测到蓝牙适配器"),
                ("err_radio_off", "蓝牙已关闭或不可用，请在系统设置中开启蓝牙后重试"),
                ("empty_title", "尚未发现心率设备"),
                ("empty_sub", "请确认设备已开启心率广播、未与手机连接，且电脑蓝牙已开启，然后点击「扫描设备」"),
                ("status_connected", "已连接"), ("status_connecting", "连接中…"), ("status_disconnected", "未连接"),
                ("connect", "连接"), ("disconnect", "断开"),
                ("unknown_device", "未知设备"),
                ("label_hr", "心率"), ("bpm", "bpm"), ("label_battery", "电量"), ("label_rr", "RR 间期 (ms)"),
                ("pick_color", "曲线颜色"),
                ("err_not_found", "未找到设备，请确认设备在广播范围内"),
                ("err_gatt", "无法建立 GATT 会话"),
                ("err_no_hr_service", "设备未提供心率服务 (0x180D)"),
                ("err_no_hr_char", "设备未提供心率测量特征 (0x2A37)"),
                ("err_subscribe", "订阅心率通知失败：{0}"),
                ("err_already", "该设备已在连接中"),
                ("status_link_lost", "设备连接已断开"),
                ("chart_title", "心率图表"),
                ("time_window", "时间窗口"),
                ("win_30", "30 秒"), ("win_1", "1 分钟"), ("win_3", "3 分钟"), ("win_5", "5 分钟"), ("win_10", "10 分钟"), ("win_15", "15 分钟"), ("win_30min", "30 分钟"), ("win_all", "全程"),
                ("max_hr", "最大心率"),
                ("show_zones", "显示区间"), ("hide_zones", "隐藏区间"),
                ("zone1", "热身"), ("zone2", "燃脂"), ("zone3", "有氧"), ("zone4", "无氧"), ("zone5", "极限"),
                ("chart_empty_title", "暂无曲线数据"),
                ("chart_empty_sub", "连接心率带并点击「开始记录」后，曲线会实时绘制在这里"),
                ("settings_title", "设置"),
                ("language", "语言"), ("language_auto", "自动跟随系统"),
                ("theme", "主题"),
                ("theme_auto", "自动跟随系统"), ("theme_light", "浅色"), ("theme_dark", "深色"),
                ("settings_hint", "更改立即生效。支持同时连接多台心率设备。"),
                ("record_start", "开始记录"), ("record_stop", "停止记录"), ("recording_elapsed", "记录中 {0}"), ("export_csv", "导出 CSV"), 
                ("edit_zones", "编辑区间"), ("zones_reset", "恢复默认"), ("cancel", "取消"),
                ("edit_y_axis", "编辑Y轴"), ("y_min", "Y 轴下限"), ("y_max", "Y 轴上限"), ("y_axis_auto", "恢复自动"),
                ("settings_about", "Heart 心率监测 · 蓝牙心率 / 电量 / RR 间期 / 实时区间曲线"),
                ("tray_restore", "回到界面"), ("tray_exit", "退出软件"),
                ("view_drop_hint", "松开导入数据"), ("view_drop_blocked", "记录中无法导入数据"),
                ("view_exit", "退出查看"),
                ("view_import_failed_title", "无法导入数据"),
                ("view_import_failed_sub", "请拖入通过「导出 CSV」保存的心率数据文件，或设备端导出的 Excel（.xlsx）记录"),
                ("legend_avg", "平均值 {0}"), ("legend_points", "有效数据点 {0}"),
                ("curve_offset", "曲线偏移"), ("offset_curve", "选择曲线"), ("offset_seconds", "向左移动（秒）"), ("mae", "误差计算"), ("mae_test", "被测设备"), ("mae_reference", "对标设备"), ("calculate", "计算"), ("mae_mae", "平均绝对误差 {0} bpm"), ("mae_used", "{0} 有效数据点"), ("mae_dropped", "{0} 舍弃数据点"), ("mae_max", "最大绝对误差 {0} bpm"), ("mae_no_data", "两条曲线没有重叠的秒"), ("done", "完成")),

            ["zh-TW"] = Dict(
                ("app_title", "心率對比"),
                ("app_file_name", "心率對比"),
                ("nav_devices", "裝置"), ("nav_chart", "即時圖表"), ("nav_settings", "設定"),
                ("devices_title", "裝置"),
                ("scan_devices", "掃描裝置"), ("stop_scan", "停止掃描"),
                ("hint_scan", "點擊「掃描裝置」搜尋正在廣播心率資料的藍牙裝置"),
                ("hint_scanning", "正在掃描… 已發現 {0} 台裝置"),
                ("hint_found", "共發現 {0} 台裝置（停止掃描後仍可連線 / 中斷）"),
                ("hint_scan_error", "藍牙掃描啟動失敗：{0}"),
                ("hint_scan_stopped", "掃描已停止：{0}"),
                ("err_no_radio", "未偵測到藍牙適配器"),
                ("err_radio_off", "藍牙已關閉或不可用，請在系統設定中開啟藍牙後重試"),
                ("empty_title", "尚未發現心率裝置"),
                ("empty_sub", "請確認裝置已開啟心率廣播、未與手機連接，且電腦藍牙已開啟，然後點擊「掃描裝置」"),
                ("status_connected", "已連線"), ("status_connecting", "連線中…"), ("status_disconnected", "未連線"),
                ("connect", "連線"), ("disconnect", "中斷"),
                ("unknown_device", "未知裝置"),
                ("label_hr", "心率"), ("bpm", "bpm"), ("label_battery", "電量"), ("label_rr", "RR 間期 (ms)"),
                ("pick_color", "曲線顏色"),
                ("err_not_found", "未找到裝置，請確認裝置在廣播範圍內"),
                ("err_gatt", "無法建立 GATT 會話"),
                ("err_no_hr_service", "裝置未提供心率服務 (0x180D)"),
                ("err_no_hr_char", "裝置未提供心率測量特徵 (0x2A37)"),
                ("err_subscribe", "訂閱心率通知失敗：{0}"),
                ("err_already", "該裝置已在連線中"),
                ("status_link_lost", "裝置連線已斷開"),
                ("chart_title", "心率圖表"),
                ("time_window", "時間視窗"),
                ("win_30", "30 秒"), ("win_1", "1 分鐘"), ("win_3", "3 分鐘"), ("win_5", "5 分鐘"), ("win_10", "10 分鐘"), ("win_15", "15 分鐘"), ("win_30min", "30 分鐘"), ("win_all", "全程"),
                ("max_hr", "最大心率"),
                ("show_zones", "顯示區間"), ("hide_zones", "隱藏區間"),
                ("zone1", "熱身"), ("zone2", "燃脂"), ("zone3", "有氧"), ("zone4", "無氧"), ("zone5", "極限"),
                ("chart_empty_title", "暫無曲線數據"),
                ("chart_empty_sub", "連接心率帶並點擊「開始記錄」後，曲線會即時繪製在這裡"),
                ("settings_title", "設定"),
                ("language", "語言"), ("language_auto", "自動跟隨系統"),
                ("theme", "主題"),
                ("theme_auto", "自動跟隨系統"), ("theme_light", "淺色"), ("theme_dark", "深色"),
                ("settings_hint", "變更立即生效。支援同時連接多台心率裝置。"),
                ("record_start", "開始記錄"), ("record_stop", "停止記錄"), ("recording_elapsed", "記錄中 {0}"), ("export_csv", "匯出 CSV"), 
                ("edit_zones", "編輯區間"), ("zones_reset", "恢復預設"), ("cancel", "取消"),
                ("edit_y_axis", "編輯Y軸"), ("y_min", "Y 軸下限"), ("y_max", "Y 軸上限"), ("y_axis_auto", "恢復自動"),
                ("settings_about", "Heart 心率監測 · 藍牙心率 / 電量 / RR 間期 / 即時區間曲線"),
                ("tray_restore", "回到介面"), ("tray_exit", "離開程式"),
                ("view_drop_hint", "放開以匯入資料"), ("view_drop_blocked", "記錄中無法匯入資料"),
                ("view_exit", "退出檢視"),
                ("view_import_failed_title", "無法匯入資料"),
                ("view_import_failed_sub", "請拖入透過「匯出 CSV」儲存的心率資料檔案，或裝置端匯出的 Excel（.xlsx）記錄"),
                ("legend_avg", "平均值 {0}"), ("legend_points", "有效資料點 {0}"),
                ("curve_offset", "曲線偏移"), ("offset_curve", "選擇曲線"), ("offset_seconds", "向左移動（秒）"), ("mae", "誤差計算"), ("mae_test", "被測設備"), ("mae_reference", "對標設備"), ("calculate", "計算"), ("mae_mae", "平均絕對誤差 {0} bpm"), ("mae_used", "{0} 有效資料點"), ("mae_dropped", "{0} 捨棄資料點"), ("mae_max", "最大絕對誤差 {0} bpm"), ("mae_no_data", "兩條曲線沒有重疊的秒"), ("done", "完成")),

            ["en-US"] = Dict(
                ("app_title", "Heart Rate Comparison"),
                ("app_file_name", "HeartRateComparison"),
                ("nav_devices", "Devices"), ("nav_chart", "Live Chart"), ("nav_settings", "Settings"),
                ("devices_title", "Devices"),
                ("scan_devices", "Scan"), ("stop_scan", "Stop scan"),
                ("hint_scan", "Click \"Scan\" to search for Bluetooth devices broadcasting heart rate data"),
                ("hint_scanning", "Scanning… {0} device(s) found"),
                ("hint_found", "{0} device(s) found (you can still connect or disconnect after stopping)"),
                ("hint_scan_error", "Bluetooth scan failed to start: {0}"),
                ("hint_scan_stopped", "Scan stopped: {0}"),
                ("err_no_radio", "No Bluetooth adapter detected"),
                ("err_radio_off", "Bluetooth is off or unavailable. Turn it on in Windows settings and try again"),
                ("empty_title", "No heart rate devices found"),
                ("empty_sub", "Make sure heart rate broadcast is enabled on the device, it is not connected to your phone, and PC Bluetooth is on, then click \"Scan\""),
                ("status_connected", "Connected"), ("status_connecting", "Connecting…"), ("status_disconnected", "Not connected"),
                ("connect", "Connect"), ("disconnect", "Disconnect"),
                ("unknown_device", "Unknown device"),
                ("label_hr", "Heart rate"), ("bpm", "bpm"), ("label_battery", "Battery"), ("label_rr", "RR intervals (ms)"),
                ("pick_color", "Curve color"),
                ("err_not_found", "Device not found. Make sure it is advertising nearby"),
                ("err_gatt", "Could not establish a GATT session"),
                ("err_no_hr_service", "Device does not expose the Heart Rate service (0x180D)"),
                ("err_no_hr_char", "Device does not expose the Heart Rate Measurement characteristic (0x2A37)"),
                ("err_subscribe", "Failed to subscribe to heart rate notifications: {0}"),
                ("err_already", "This device is already connecting"),
                ("status_link_lost", "Device connection lost"),
                ("chart_title", "Heart Rate Chart"),
                ("time_window", "Time window"),
                ("win_30", "30 s"), ("win_1", "1 min"), ("win_3", "3 min"), ("win_5", "5 min"), ("win_10", "10 min"), ("win_15", "15 min"), ("win_30min", "30 min"), ("win_all", "Full"),
                ("max_hr", "Max heart rate"),
                ("show_zones", "Zones shown"), ("hide_zones", "Zones hidden"),
                ("zone1", "Warm-up"), ("zone2", "Fat burn"), ("zone3", "Aerobic"), ("zone4", "Anaerobic"), ("zone5", "Maximum"),
                ("chart_empty_title", "No curve data yet"),
                ("chart_empty_sub", "Connect a heart rate strap and start recording; curves will be drawn here in real time"),
                ("settings_title", "Settings"),
                ("language", "Language"), ("language_auto", "Follow system"),
                ("theme", "Theme"),
                ("theme_auto", "Follow system"), ("theme_light", "Light"), ("theme_dark", "Dark"),
                ("settings_hint", "Changes apply immediately. Multiple heart rate devices can be connected at the same time."),
                ("record_start", "Start Recording"), ("record_stop", "Stop Recording"), ("recording_elapsed", "Recording {0}"), ("export_csv", "Export CSV"), 
                ("edit_zones", "Edit zones"), ("zones_reset", "Reset to defaults"), ("cancel", "Cancel"),
                ("edit_y_axis", "Edit Y-axis"), ("y_min", "Y minimum"), ("y_max", "Y maximum"), ("y_axis_auto", "Back to auto"),
                ("settings_about", "Heart Heart Rate Monitor · Bluetooth HR / battery / RR intervals / live zone chart"),
                ("tray_restore", "Show Window"), ("tray_exit", "Exit App"),
                ("view_drop_hint", "Drop to view data"), ("view_drop_blocked", "Cannot import while recording"),
                ("view_exit", "Exit view"),
                ("view_import_failed_title", "Cannot import data"),
                ("view_import_failed_sub", "Drop a heart rate CSV file saved via \"Export CSV\", or an Excel (.xlsx) recording exported by your device"),
                ("legend_avg", "Average {0}"), ("legend_points", "{0} valid points"),
                ("curve_offset", "Curve offset"), ("offset_curve", "Curve"), ("offset_seconds", "Shift left (s)"), ("mae", "Error (MAE)"), ("mae_test", "Tested device"), ("mae_reference", "Reference device"), ("calculate", "Calculate"), ("mae_mae", "Mean abs. error {0} bpm"), ("mae_used", "{0} valid points"), ("mae_dropped", "{0} dropped"), ("mae_max", "Max abs. error {0} bpm"), ("mae_no_data", "No overlapping seconds between the two curves"), ("done", "Done")),

            ["ja-JP"] = Dict(
                ("app_title", "心拍数比較"),
                ("app_file_name", "心拍数比較"),
                ("nav_devices", "デバイス"), ("nav_chart", "リアルタイムチャート"), ("nav_settings", "設定"),
                ("devices_title", "デバイス"),
                ("scan_devices", "スキャン"), ("stop_scan", "スキャン停止"),
                ("hint_scan", "「スキャン」をクリックすると、心拍数をブロードキャストしているBluetoothデバイスを検索します"),
                ("hint_scanning", "スキャン中… {0} 台見つかりました"),
                ("hint_found", "{0} 台見つかりました（スキャン停止後も接続/切断できます）"),
                ("hint_scan_error", "Bluetoothスキャンの開始に失敗しました：{0}"),
                ("hint_scan_stopped", "スキャンが停止しました：{0}"),
                ("err_no_radio", "Bluetoothアダプターが検出されません"),
                ("err_radio_off", "Bluetoothがオフか利用できません。設定でオンにしてから再試行してください"),
                ("empty_title", "心拍数デバイスが見つかりません"),
                ("empty_sub", "デバイスで心拍数ブロードキャストを有効にし、スマホとの接続を解除し、PCのBluetoothがオンになっているか確認してから「スキャン」をクリックしてください"),
                ("status_connected", "接続済み"), ("status_connecting", "接続中…"), ("status_disconnected", "未接続"),
                ("connect", "接続"), ("disconnect", "切断"),
                ("unknown_device", "不明なデバイス"),
                ("label_hr", "心拍数"), ("bpm", "bpm"), ("label_battery", "バッテリー"), ("label_rr", "RR間隔 (ms)"),
                ("pick_color", "曲線の色"),
                ("err_not_found", "デバイスが見つかりません。近くでアドバタイズしているか確認してください"),
                ("err_gatt", "GATTセッションを確立できません"),
                ("err_no_hr_service", "デバイスが心拍数サービス (0x180D) を提供していません"),
                ("err_no_hr_char", "心拍数測定キャラクタリスティック (0x2A37) がありません"),
                ("err_subscribe", "心拍数通知の購読に失敗しました：{0}"),
                ("err_already", "このデバイスはすでに接続中です"),
                ("status_link_lost", "デバイスの接続が切断されました"),
                ("chart_title", "心拍数チャート"),
                ("time_window", "時間窓"),
                ("win_30", "30秒"), ("win_1", "1分"), ("win_3", "3分"), ("win_5", "5分"), ("win_10", "10分"), ("win_15", "15分"), ("win_30min", "30分"), ("win_all", "全期間"),
                ("max_hr", "最大心拍数"),
                ("show_zones", "ゾーン表示"), ("hide_zones", "ゾーン非表示"),
                ("zone1", "ウォームアップ"), ("zone2", "脂肪燃焼"), ("zone3", "有酸素"), ("zone4", "無酸素"), ("zone5", "最大"),
                ("chart_empty_title", "チャートデータがありません"),
                ("chart_empty_sub", "心拍ストラップを接続し「記録開始」を押すと、ここにリアルタイムで描画されます"),
                ("settings_title", "設定"),
                ("language", "言語"), ("language_auto", "システムに従う"),
                ("theme", "テーマ"),
                ("theme_auto", "システムに従う"), ("theme_light", "ライト"), ("theme_dark", "ダーク"),
                ("settings_hint", "変更はすぐに反映されます。複数の心拍デバイスを同時接続できます。"),
                ("record_start", "記録開始"), ("record_stop", "記録停止"), ("recording_elapsed", "記録中 {0}"), ("export_csv", "CSVエクスポート"), 
                ("edit_zones", "ゾーン編集"), ("zones_reset", "デフォルトに戻す"), ("cancel", "キャンセル"),
                ("edit_y_axis", "Y軸編集"), ("y_min", "Y軸下限"), ("y_max", "Y軸上限"), ("y_axis_auto", "自動に戻す"),
                ("settings_about", "Heart 心拍数モニター · Bluetooth心拍/バッテリー/RR間隔/リアルタイムゾーンチャート"),
                ("tray_restore", "画面に戻る"), ("tray_exit", "アプリを終了"),
                ("view_drop_hint", "ドロップしてデータを表示"), ("view_drop_blocked", "記録中はデータを読み込めません"),
                ("view_exit", "表示を終了"),
                ("view_import_failed_title", "データを読み込めません"),
                ("view_import_failed_sub", "「CSVエクスポート」で保存した心拍データファイル、またはデバイスが書き出した Excel（.xlsx）記録をドロップしてください"),
                ("legend_avg", "平均値 {0}"), ("legend_points", "有効データ点数 {0}"),
                ("curve_offset", "曲線のオフセット"), ("offset_curve", "曲線を選択"), ("offset_seconds", "左に移動（秒）"), ("mae", "誤差 (MAE)"), ("mae_test", "被測定デバイス"), ("mae_reference", "基準デバイス"), ("calculate", "計算"), ("mae_mae", "平均絶対誤差 {0} bpm"), ("mae_used", "有効点 {0}"), ("mae_dropped", "除外点 {0}"), ("mae_max", "最大絶対誤差 {0} bpm"), ("mae_no_data", "2つの曲線間に重複する秒がありません"), ("done", "完了")),

            ["ko-KR"] = Dict(
                ("app_title", "심박수 비교"),
                ("app_file_name", "심박수비교"),
                ("nav_devices", "기기"), ("nav_chart", "실시간 차트"), ("nav_settings", "설정"),
                ("devices_title", "기기"),
                ("scan_devices", "스캔"), ("stop_scan", "스캔 중지"),
                ("hint_scan", "「스캔」을 클릭하면 심박수를 광고하는 블루투스 기기를 검색합니다"),
                ("hint_scanning", "스캔 중… {0}개 기기를 찾았습니다"),
                ("hint_found", "{0}개 기기를 찾았습니다 (스캔 중지 후에도 연결/해제 가능)"),
                ("hint_scan_error", "블루투스 스캔 시작 실패: {0}"),
                ("hint_scan_stopped", "스캔이 중지되었습니다: {0}"),
                ("err_no_radio", "블루투스 어댑터를 찾을 수 없습니다"),
                ("err_radio_off", "블루투스가 꺼져 있거나 사용할 수 없습니다. 설정에서 켠 후 다시 시도하세요"),
                ("empty_title", "심박수 기기를 찾지 못했습니다"),
                ("empty_sub", "기기에서 심박수 브로드캐스트를 켜고 휴대전화와의 연결을 끊으며, PC 블루투스가 켜져 있는지 확인한 후 「스캔」을 클릭하세요"),
                ("status_connected", "연결됨"), ("status_connecting", "연결 중…"), ("status_disconnected", "연결 안 됨"),
                ("connect", "연결"), ("disconnect", "연결 해제"),
                ("unknown_device", "알 수 없는 기기"),
                ("label_hr", "심박수"), ("bpm", "bpm"), ("label_battery", "배터리"), ("label_rr", "RR 간격 (ms)"),
                ("pick_color", "곡선 색상"),
                ("err_not_found", "기기를 찾을 수 없습니다. 근처에서 광고 중인지 확인하세요"),
                ("err_gatt", "GATT 세션을 생성할 수 없습니다"),
                ("err_no_hr_service", "기기가 심박수 서비스 (0x180D)를 제공하지 않습니다"),
                ("err_no_hr_char", "심박수 측정 특성 (0x2A37)이 없습니다"),
                ("err_subscribe", "심박수 알림 구독 실패: {0}"),
                ("err_already", "이 기기는 이미 연결 중입니다"),
                ("status_link_lost", "기기 연결이 끊어졌습니다"),
                ("chart_title", "심박수 차트"),
                ("time_window", "시간 창"),
                ("win_30", "30초"), ("win_1", "1분"), ("win_3", "3분"), ("win_5", "5분"), ("win_10", "10분"), ("win_15", "15분"), ("win_30min", "30분"), ("win_all", "전체"),
                ("max_hr", "최대 심박수"),
                ("show_zones", "구간 표시"), ("hide_zones", "구간 숨김"),
                ("zone1", "워밍업"), ("zone2", "지방 연소"), ("zone3", "유산소"), ("zone4", "무산소"), ("zone5", "최대"),
                ("chart_empty_title", "곡선 데이터가 없습니다"),
                ("chart_empty_sub", "심박 벨트를 연결하고 「기록 시작」을 누르면 여기에 실시간으로 그려집니다"),
                ("settings_title", "설정"),
                ("language", "언어"), ("language_auto", "시스템 따르기"),
                ("theme", "테마"),
                ("theme_auto", "시스템 따르기"), ("theme_light", "라이트"), ("theme_dark", "다크"),
                ("settings_hint", "변경 사항이 즉시 적용됩니다. 여러 심박 기기를 동시에 연결할 수 있습니다."),
                ("record_start", "기록 시작"), ("record_stop", "기록 중지"), ("recording_elapsed", "기록 중 {0}"), ("export_csv", "CSV 내보내기"), 
                ("edit_zones", "구간 편집"), ("zones_reset", "기본값으로"), ("cancel", "취소"),
                ("edit_y_axis", "Y축 편집"), ("y_min", "Y축 최솟값"), ("y_max", "Y축 최댓값"), ("y_axis_auto", "자동으로"),
                ("settings_about", "Heart 심박수 모니터 · 블루투스 심박/배터리/RR 간격/실시간 구간 차트"),
                ("tray_restore", "화면으로 돌아가기"), ("tray_exit", "앱 종료"),
                ("view_drop_hint", "놓아서 데이터 가져오기"), ("view_drop_blocked", "기록 중에는 데이터를 가져올 수 없습니다"),
                ("view_exit", "보기 종료"),
                ("view_import_failed_title", "데이터를 가져올 수 없습니다"),
                ("view_import_failed_sub", "「CSV 내보내기」로 저장한 심박 데이터 파일 또는 기기에서 내보낸 Excel(.xlsx) 기록을 드롭하세요"),
                ("legend_avg", "평균값 {0}"), ("legend_points", "유효 데이터 포인트 {0}"),
                ("curve_offset", "곡선 오프셋"), ("offset_curve", "곡선 선택"), ("offset_seconds", "왼쪽으로 이동(초)"), ("mae", "오차 (MAE)"), ("mae_test", "측정 기기"), ("mae_reference", "기준 기기"), ("calculate", "계산"), ("mae_mae", "평균 절대 오차 {0} bpm"), ("mae_used", "유효 점 {0}"), ("mae_dropped", "제외 점 {0}"), ("mae_max", "최대 절대 오차 {0} bpm"), ("mae_no_data", "두 곡선 사이에 겹치는 초가 없습니다"), ("done", "완료")),

            ["fr-FR"] = Dict(
                ("app_title", "Comparaison de fréquence cardiaque"),
                ("app_file_name", "ComparaisonFC"),
                ("nav_devices", "Appareils"), ("nav_chart", "Graphique temps réel"), ("nav_settings", "Paramètres"),
                ("devices_title", "Appareils"),
                ("scan_devices", "Scanner"), ("stop_scan", "Arrêter l'analyse"),
                ("hint_scan", "Cliquez sur « Scanner » pour rechercher les appareils Bluetooth diffusant la fréquence cardiaque"),
                ("hint_scanning", "Analyse… {0} appareil(s) trouvé(s)"),
                ("hint_found", "{0} appareil(s) trouvé(s) (connexion/déconnexion possible après l'arrêt)"),
                ("hint_scan_error", "Échec du démarrage de l'analyse Bluetooth : {0}"),
                ("hint_scan_stopped", "Analyse arrêtée : {0}"),
                ("err_no_radio", "Aucun adaptateur Bluetooth détecté"),
                ("err_radio_off", "Le Bluetooth est désactivé ou indisponible. Activez-le dans les paramètres Windows puis réessayez"),
                ("empty_title", "Aucun appareil cardiaque trouvé"),
                ("empty_sub", "Assurez-vous que la diffusion de la fréquence cardiaque est activée, que l'appareil n'est pas connecté au téléphone et que le Bluetooth du PC est actif, puis cliquez sur « Scanner »"),
                ("status_connected", "Connecté"), ("status_connecting", "Connexion…"), ("status_disconnected", "Non connecté"),
                ("connect", "Connecter"), ("disconnect", "Déconnecter"),
                ("unknown_device", "Appareil inconnu"),
                ("label_hr", "Fréquence cardiaque"), ("bpm", "bpm"), ("label_battery", "Batterie"), ("label_rr", "Intervalles RR (ms)"),
                ("pick_color", "Couleur de la courbe"),
                ("err_not_found", "Appareil introuvable. Vérifiez qu'il diffuse à proximité"),
                ("err_gatt", "Impossible d'établir une session GATT"),
                ("err_no_hr_service", "L'appareil n'expose pas le service Fréquence cardiaque (0x180D)"),
                ("err_no_hr_char", "La caractéristique de mesure cardiaque (0x2A37) est absente"),
                ("err_subscribe", "Échec de l'abonnement aux notifications cardiaques : {0}"),
                ("err_already", "Cet appareil est déjà en cours de connexion"),
                ("status_link_lost", "Connexion à l'appareil perdue"),
                ("chart_title", "Graphique de fréquence cardiaque"),
                ("time_window", "Fenêtre temporelle"),
                ("win_30", "30 s"), ("win_1", "1 min"), ("win_3", "3 min"), ("win_5", "5 min"), ("win_10", "10 min"), ("win_15", "15 min"), ("win_30min", "30 min"), ("win_all", "Tout"),
                ("max_hr", "FC max"),
                ("show_zones", "Zones affichées"), ("hide_zones", "Zones masquées"),
                ("zone1", "Échauffement"), ("zone2", "Brûlage des graisses"), ("zone3", "Aérobie"), ("zone4", "Anaérobie"), ("zone5", "Maximum"),
                ("chart_empty_title", "Aucune donnée de courbe"),
                ("chart_empty_sub", "Connectez une ceinture et lancez l'enregistrement ; les courbes s'afficheront ici en temps réel"),
                ("settings_title", "Paramètres"),
                ("language", "Langue"), ("language_auto", "Suivre le système"),
                ("theme", "Thème"),
                ("theme_auto", "Suivre le système"), ("theme_light", "Clair"), ("theme_dark", "Sombre"),
                ("settings_hint", "Les changements s'appliquent immédiatement. Plusieurs appareils peuvent être connectés en même temps."),
                ("record_start", "Démarrer l'enregistrement"), ("record_stop", "Arrêter l'enregistrement"), ("recording_elapsed", "Enregistrement {0}"), ("export_csv", "Exporter CSV"), 
                ("edit_zones", "Modifier les zones"), ("zones_reset", "Réinitialiser"), ("cancel", "Annuler"),
                ("edit_y_axis", "Modifier l'axe Y"), ("y_min", "Y minimum"), ("y_max", "Y maximum"), ("y_axis_auto", "Retour à l'auto"),
                ("settings_about", "Heart Suivi cardiaque · Bluetooth FC / batterie / intervalles RR / graphique de zones en temps réel"),
                ("tray_restore", "Afficher la fenêtre"), ("tray_exit", "Quitter l'application"),
                ("view_drop_hint", "Déposer pour voir les données"), ("view_drop_blocked", "Import impossible pendant l'enregistrement"),
                ("view_exit", "Quitter la vue"),
                ("view_import_failed_title", "Impossible d'importer les données"),
                ("view_import_failed_sub", "Déposez un fichier CSV de fréquence cardiaque enregistré via « Exporter CSV », ou un enregistrement Excel (.xlsx) exporté par votre appareil"),
                ("legend_avg", "Moyenne {0}"), ("legend_points", "{0} points valides"),
                ("curve_offset", "Décalage de courbe"), ("offset_curve", "Courbe"), ("offset_seconds", "Décaler à gauche (s)"), ("mae", "Erreur (MAE)"), ("mae_test", "Appareil testé"), ("mae_reference", "Appareil de référence"), ("calculate", "Calculer"), ("mae_mae", "Erreur abs. moy. {0} bpm"), ("mae_used", "{0} points valides"), ("mae_dropped", "{0} ignorés"), ("mae_max", "Erreur abs. max. {0} bpm"), ("mae_no_data", "Aucune seconde en commun entre les deux courbes"), ("done", "Terminé")),

            ["de-DE"] = Dict(
                ("app_title", "Herzfrequenzvergleich"),
                ("app_file_name", "Herzfrequenzvergleich"),
                ("nav_devices", "Geräte"), ("nav_chart", "Echtzeit-Diagramm"), ("nav_settings", "Einstellungen"),
                ("devices_title", "Geräte"),
                ("scan_devices", "Scannen"), ("stop_scan", "Scan anhalten"),
                ("hint_scan", "Klicken Sie auf „Scannen“, um Bluetooth-Geräte mit Herzfrequenz-Broadcast zu suchen"),
                ("hint_scanning", "Scanne… {0} Gerät(e) gefunden"),
                ("hint_found", "{0} Gerät(e) gefunden (nach dem Anhalten kann weiterhin verbunden werden)"),
                ("hint_scan_error", "Bluetooth-Scan konnte nicht gestartet werden: {0}"),
                ("hint_scan_stopped", "Scan angehalten: {0}"),
                ("err_no_radio", "Kein Bluetooth-Adapter erkannt"),
                ("err_radio_off", "Bluetooth ist aus oder nicht verfügbar. Aktivieren Sie es in den Windows-Einstellungen und versuchen Sie es erneut"),
                ("empty_title", "Keine Herzfrequenz-Geräte gefunden"),
                ("empty_sub", "Stellen Sie sicher, dass die Herzfrequenz-Übertragung am Gerät aktiviert ist, das Gerät nicht mit dem Telefon verbunden ist und der PC-Bluetooth-Adapter eingeschaltet ist, und klicken Sie dann auf „Scannen“"),
                ("status_connected", "Verbunden"), ("status_connecting", "Verbinden…"), ("status_disconnected", "Nicht verbunden"),
                ("connect", "Verbinden"), ("disconnect", "Trennen"),
                ("unknown_device", "Unbekanntes Gerät"),
                ("label_hr", "Herzfrequenz"), ("bpm", "bpm"), ("label_battery", "Akku"), ("label_rr", "RR-Intervalle (ms)"),
                ("pick_color", "Kurvenfarbe"),
                ("err_not_found", "Gerät nicht gefunden. Bitte sicherstellen, dass es in Reichweite sendet"),
                ("err_gatt", "GATT-Sitzung konnte nicht erstellt werden"),
                ("err_no_hr_service", "Gerät stellt keinen Herzfrequenz-Dienst (0x180D) bereit"),
                ("err_no_hr_char", "Herzfrequenz-Messmerkmal (0x2A37) fehlt"),
                ("err_subscribe", "Abonnieren der Herzfrequenz-Benachrichtigungen fehlgeschlagen: {0}"),
                ("err_already", "Dieses Gerät verbindet sich bereits"),
                ("status_link_lost", "Geräteverbindung verloren"),
                ("chart_title", "Herzfrequenz-Diagramm"),
                ("time_window", "Zeitfenster"),
                ("win_30", "30 Sek."), ("win_1", "1 Min."), ("win_3", "3 Min."), ("win_5", "5 Min."), ("win_10", "10 Min."), ("win_15", "15 Min."), ("win_30min", "30 Min."), ("win_all", "Gesamt"),
                ("max_hr", "Max. Herzfrequenz"),
                ("show_zones", "Zonen angezeigt"), ("hide_zones", "Zonen ausgeblendet"),
                ("zone1", "Aufwärmung"), ("zone2", "Fettverbrennung"), ("zone3", "Aerob"), ("zone4", "Anaerob"), ("zone5", "Maximum"),
                ("chart_empty_title", "Noch keine Kurvendaten"),
                ("chart_empty_sub", "Verbinde ein Herzfrequenzband und starte die Aufzeichnung; die Kurven werden hier live gezeichnet"),
                ("settings_title", "Einstellungen"),
                ("language", "Sprache"), ("language_auto", "System folgen"),
                ("theme", "Design"),
                ("theme_auto", "System folgen"), ("theme_light", "Hell"), ("theme_dark", "Dunkel"),
                ("settings_hint", "Änderungen werden sofort übernommen. Mehrere Herzfrequenz-Geräte können gleichzeitig verbunden werden."),
                ("record_start", "Aufnahme starten"), ("record_stop", "Aufnahme beenden"), ("recording_elapsed", "Aufnahme {0}"), ("export_csv", "CSV exportieren"), 
                ("edit_zones", "Zonen bearbeiten"), ("zones_reset", "Zurücksetzen"), ("cancel", "Abbrechen"),
                ("edit_y_axis", "Y-Achse bearbeiten"), ("y_min", "Y-Minimum"), ("y_max", "Y-Maximum"), ("y_axis_auto", "Zurück zu automatisch"),
                ("settings_about", "Heart Herzfrequenz-Monitor · Bluetooth HF / Akku / RR-Intervalle / Live-Zonendiagramm"),
                ("tray_restore", "Fenster anzeigen"), ("tray_exit", "App beenden"),
                ("view_drop_hint", "Loslassen, um Daten anzuzeigen"), ("view_drop_blocked", "Import während der Aufnahme nicht möglich"),
                ("view_exit", "Ansicht beenden"),
                ("view_import_failed_title", "Daten konnten nicht geladen werden"),
                ("view_import_failed_sub", "Legen Sie eine über „CSV exportieren“ gespeicherte Herzfrequenz-CSV oder eine vom Gerät exportierte Excel-Datei (.xlsx) hier ab"),
                ("legend_avg", "Mittelwert {0}"), ("legend_points", "{0} gültige Punkte"),
                ("curve_offset", "Kurvenversatz"), ("offset_curve", "Kurve"), ("offset_seconds", "Nach links (s)"), ("mae", "Fehler (MAE)"), ("mae_test", "Getestetes Gerät"), ("mae_reference", "Referenz"), ("calculate", "Berechnen"), ("mae_mae", "Mittl. abs. Fehler {0} bpm"), ("mae_used", "{0} gültige Pkt."), ("mae_dropped", "{0} ignoriert"), ("mae_max", "Max. abs. Fehler {0} bpm"), ("mae_no_data", "Keine überlappenden Sekunden zwischen den Kurven"), ("done", "Fertig")),

            ["es-ES"] = Dict(
                ("app_title", "Comparación de frecuencia cardíaca"),
                ("app_file_name", "ComparacionFC"),
                ("nav_devices", "Dispositivos"), ("nav_chart", "Gráfico en tiempo real"), ("nav_settings", "Ajustes"),
                ("devices_title", "Dispositivos"),
                ("scan_devices", "Escanear"), ("stop_scan", "Detener"),
                ("hint_scan", "Pulsa «Escanear» para buscar dispositivos Bluetooth que difunden ritmo cardíaco"),
                ("hint_scanning", "Escaneando… {0} dispositivo(s) encontrado(s)"),
                ("hint_found", "{0} dispositivo(s) encontrado(s) (puedes conectar o desconectar tras detener)"),
                ("hint_scan_error", "Error al iniciar el escaneo Bluetooth: {0}"),
                ("hint_scan_stopped", "Escaneo detenido: {0}"),
                ("err_no_radio", "No se ha detectado ningún adaptador Bluetooth"),
                ("err_radio_off", "El Bluetooth está apagado o no disponible. Actívalo en la configuración de Windows y reintenta"),
                ("empty_title", "No se han encontrado dispositivos de ritmo cardíaco"),
                ("empty_sub", "Asegúrate de que la difusión de ritmo cardíaco esté activada en el dispositivo, que no esté conectado al móvil y que el Bluetooth del PC esté encendido; después pulsa «Escanear»"),
                ("status_connected", "Conectado"), ("status_connecting", "Conectando…"), ("status_disconnected", "Desconectado"),
                ("connect", "Conectar"), ("disconnect", "Desconectar"),
                ("unknown_device", "Dispositivo desconocido"),
                ("label_hr", "Ritmo cardíaco"), ("bpm", "ppm"), ("label_battery", "Batería"), ("label_rr", "Intervalos RR (ms)"),
                ("pick_color", "Color de la curva"),
                ("err_not_found", "Dispositivo no encontrado. Comprueba que está cerca difundiendo"),
                ("err_gatt", "No se pudo establecer la sesión GATT"),
                ("err_no_hr_service", "El dispositivo no ofrece el servicio de ritmo cardíaco (0x180D)"),
                ("err_no_hr_char", "Falta la característica de medida de ritmo cardíaco (0x2A37)"),
                ("err_subscribe", "Error al suscribirse a las notificaciones de ritmo cardíaco: {0}"),
                ("err_already", "Este dispositivo ya se está conectando"),
                ("status_link_lost", "Conexión del dispositivo perdida"),
                ("chart_title", "Gráfico de ritmo cardíaco"),
                ("time_window", "Ventana de tiempo"),
                ("win_30", "30 s"), ("win_1", "1 min"), ("win_3", "3 min"), ("win_5", "5 min"), ("win_10", "10 min"), ("win_15", "15 min"), ("win_30min", "30 min"), ("win_all", "Todo"),
                ("max_hr", "FC máx."),
                ("show_zones", "Zonas visibles"), ("hide_zones", "Zonas ocultas"),
                ("zone1", "Calentamiento"), ("zone2", "Quema de grasa"), ("zone3", "Aeróbico"), ("zone4", "Anaeróbico"), ("zone5", "Máximo"),
                ("chart_empty_title", "Aún no hay datos de curvas"),
                ("chart_empty_sub", "Conecta una banda y pulsa «Iniciar grabación»; las curvas se dibujarán aquí en tiempo real"),
                ("settings_title", "Ajustes"),
                ("language", "Idioma"), ("language_auto", "Seguir el sistema"),
                ("theme", "Tema"),
                ("theme_auto", "Seguir el sistema"), ("theme_light", "Claro"), ("theme_dark", "Oscuro"),
                ("settings_hint", "Los cambios se aplican al instante. Se pueden conectar varios dispositivos a la vez."),
                ("record_start", "Iniciar grabación"), ("record_stop", "Detener grabación"), ("recording_elapsed", "Grabando {0}"), ("export_csv", "Exportar CSV"), 
                ("edit_zones", "Editar zonas"), ("zones_reset", "Restablecer"), ("cancel", "Cancelar"),
                ("edit_y_axis", "Editar eje Y"), ("y_min", "Y mínimo"), ("y_max", "Y máximo"), ("y_axis_auto", "Volver a automático"),
                ("settings_about", "Heart Monitor de ritmo cardíaco · Bluetooth FC / batería / intervalos RR / gráfico de zonas en tiempo real"),
                ("tray_restore", "Mostrar la ventana"), ("tray_exit", "Salir de la aplicación"),
                ("view_drop_hint", "Suelta para ver los datos"), ("view_drop_blocked", "No se puede importar mientras se graba"),
                ("view_exit", "Salir de la vista"),
                ("view_import_failed_title", "No se pueden importar los datos"),
                ("view_import_failed_sub", "Suelta un archivo CSV de ritmo cardíaco guardado con «Exportar CSV» o un registro Excel (.xlsx) exportado por tu dispositivo"),
                ("legend_avg", "Media {0}"), ("legend_points", "{0} puntos válidos"),
                ("curve_offset", "Desplazamiento de curva"), ("offset_curve", "Curva"), ("offset_seconds", "Mover a la izquierda (s)"), ("mae", "Error (MAE)"), ("mae_test", "Dispositivo bajo prueba"), ("mae_reference", "Referencia"), ("calculate", "Calcular"), ("mae_mae", "Error abs. medio {0} bpm"), ("mae_used", "{0} puntos válidos"), ("mae_dropped", "{0} descartados"), ("mae_max", "Error abs. máx. {0} bpm"), ("mae_no_data", "No hay segundos coincidentes entre las dos curvas"), ("done", "Listo")),
        };
    }
}
